config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root  'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  delete  '/logout', to:  'sessions#destroy'
  post  '/signup', to: 'users#create'
  # get   'static_pages/home'
  resources :users, only: [:new, :create, :show]
  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :movements, only: [:new, :create, :destroy]
  resources :movements do
    get :autocomplete_product_name, :on => :collection
  end
end

app/models/movement.rb
# frozen_string_literal: true

class Movement < ApplicationRecord
  include Discard::Model
  belongs_to :user
  # belongs_to :products
  default_scope -> { order(created_at: :desc) }
  default_scope -> { kept }
  validates :product_id, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true }
  validates :depot_id, presence: true
end

app/controllers/movements_controller.rb
# frozen_string_literal: true

class MovementsController < ApplicationController
  before_action :logged_in_user, only: %i[new create]
  autocomplete :product, :name, full: true, limit: 5

  def new
    @movement = Movement.new
  end

  def create
    @movement = current_user.movements.build(movement_params)
    if @movement.save
      @new_qty_stock = Movement.where(product_id: @movement.product_id).sum(:quantity)
      @product = Product.find(@movement.product_id)
      @product&.update_attribute(:qtystock, @new_qty_stock)
      # if @product
      #   @product.update_attribute(:qtystock, @new_qty_stock)
      # end
      # @new_qty_stock = Movement.sum(:product_id, :conditions => {:product_id => [8]})
      flash[:success] = "Movement saved"
      redirect_to products_url
    else
      render 'movements/new'
    end
  end

  private

  def movement_params
    params.require(:movement).permit(:quantity, :product_id, :depot_id)
  end
end

app/helpers/movements_helper.rb
# frozen_string_literal: true

module MovementsHelper
end

app/views/movements/_movement.html.erb
<tr>
  <td><%= movement.quantity %></td>
  <td><%= movement.created_at.to_s(:custom_datetime) %></td>
  <td><%= movement.user.name %></td>
  <td><%= movement.depot_id %></td>
</tr>

app/views/movements/new.html.erb
<%= provide(:title, 'Add movement') %>
<h1>Add Movement</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="products-search">
      <input type="text" id="products-search-txt" autofocus>
      <div class="results" id="products-search-results"></div>
    </div>
    <%= form_for(@movement, url: movements_path) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= f.hidden_field :product_id %>

      <%= f.label :quantity %>
      <%= f.number_field :quantity, class: 'form-control' %>

      <%= f.label :depot_id %>
      <%= f.text_field :depot_id, class: 'form-control', value: '1' %>

      <%= f.submit "Save product", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		var counter = 0;


		$('#products-search-txt').typeahead({
					source: function(typeahead, query) {
						$.ajax({
							url: "/products",
							dataType: "json",
							type: "GET",
							data: {search_key: query},
							success: function(data) {
								var return_list = [], i = data.length;
									while (i--) {
									return_list[i] = {id: data[i].id, value: data[i].name, int_code: data[i].int_code, brand: data[i].brand, qty_package: data[i].qty_package, qta: data[i].qta };
									}
							typeahead.process(return_list);
							}
						});
					},
				onselect: function(obj) {
					if(counter == 10){
						alert("Numero massimo di prodotti: 10");
						return false;
					}
					// $('input[id="DossierClientId"]').val(obj.id);

					$('#MovName2').val('');
					$('#productInfo2').remove();
					$('#movement_product_id').val( obj.id );
					$('#MovIntCode').val( obj.int_code );
					$('#MovName').val( obj.value );
					$('#MovBrand').val( obj.brand );
					$('#MovQtyPackage').val( obj.qty_package );

				}
		});


	});
</script>