config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root  'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  delete  '/logout', to:  'sessions#destroy'
  post  '/signup', to: 'users#create'
  # get   'static_pages/home'
  resources :users, only: [:new, :create, :show]
  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :movements, only: [:new, :create, :destroy]
  resources :movements do
    get :autocomplete_product_name, :on => :collection
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  include Discard::Model
  belongs_to :user
  has_many :movements, dependent: :destroy
  default_scope -> { order(product_code: :asc) }
  default_scope -> { kept }
  before_save { self.product_code = product_code.upcase }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 100 }
  validates :price, presence: true, numericality: true
  validates :qtystock, presence: true, numericality: { only_integer: true }
  validates :product_code, presence: true, uniqueness: { case_sensitive: false }
  validate :validate_picture_size

  after_discard do
    movements.discard_all
  end

  after_undiscard do
    movements.undiscard_all
  end

  def getmovements
    Movement.where('products_id = ?', id)
  end

  def self.search(term)
    where('name ILIKE :term OR product_code ILIKE :term', term: "%#{term}%")
  end

  private

  # def picture_size
  #   if picture.size > 1.megabytes
  #     errors.add(:picture, "should be less than 1MB")
  #   end
  # end

  def validate_picture_size
    return if picture.size <= 1.megabytes

    errors.add(:picture, "should be less than 1MB")
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :logged_in_user, only: %i[index show new create edit update destroy]
  before_action :admin_user, only: :destroy

  def index
    respond_to do |format|
      format.html { @products = Product.paginate(page: params[:page], per_page: 2) }
      format.json { @products = Product.search(params[:term]) }
    end
  end

  def show
    @product = Product.find(params[:id])
    @movements = @product.movements
    # @movements = Movement.find_by(products_id: params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.build(product_params)
    if @product.save
      flash[:success] = 'Product saved'
      redirect_to products_url
    else
      render 'products/new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:success] = "Product modified"
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    Product.find(params[:id]).discard
    flash[:success] = "Product deleted"
    redirect_to products_url
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :qtystock, :product_code, :picture)
  end

  def admin_user
    redirect_to(products_url) unless current_user.admin?
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :product_code %>
  <%= f.text_field :product_code, class: "form-control" %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>

  <%= f.label :price %>
  <%= f.text_field :price, class: "form-control" %>

  <%= f.label :qtystock %>
  <%= f.number_field :qtystock, class: "form-control" %>

  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>

  <%= f.submit "Save product", class: "btn btn-primary" %>
<% end %>

app/views/products/edit.html.erb
<%= provide(:title, 'Edit Product') %>
<h1>Edit Product</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

<script type="text/javascript">
  $('#product_picture').bind('change', function() {
    var size_in_megabyte = this.files[0].size/1024/1024;
    if (size_in_megabyte > 1) {
      alert('Maximum file size is 1MB');
    }
  });
</script>

app/views/products/index.html.erb
<%= provide(:title, 'Products list') %>
<h1>All Products</h1>

<%= will_paginate %>

<table class="table table-bordered products">
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Qty Stock</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.product_code, product %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %> €</td>
        <td><%= product.qtystock %></td>
        <td>
          <%= link_to "Show", product %>
          <% if current_user.admin? %>
            | <%= link_to "Edit", edit_product_path(product) %> 
            | <%= link_to "Delete", product, method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

app/views/products/new.html.erb
<%= provide(:title, 'New Product') %>
<h1>New Product</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

<script type="text/javascript">
  $('#product_picture').bind('change', function() {
    var size_in_megabyte = this.files[0].size/1024/1024;
    if (size_in_megabyte > 1) {
      alert('Maximum file size is 1MB');
    }
  });
</script>

app/views/products/show.html.erb
<% provide(:title, 'Product details') %>
<h1>Product details: <%= @product.name %></h1>

<div class="row">
  <aside class="col-md-4">
    <section class="product_img">
      <%= image_tag @product.picture.url if @product.picture? %>
    </section>
    <section class="product_info">
      <p>Code: <%= @product.product_code %></p>
      <p>Name: <%= @product.name %></p>
      <p>Description: <%= @product.description %></p>
      <p>Price: <%= @product.price %></p>
      <p>Qty in Stock: <%= @product.qtystock %></p>
    </section>
  </aside>
  <div class="col-md-8">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Movements</h3>
      </div>

      <table class="table">
        <thead>
          <tr>
            <th>Quantity</th>
            <th>Date</th>
            <th>User</th>
            <th>Depot</th>
          </tr>
        </thead>
        <tbody>
          <% if @product.movements.any? %>
            <%= render @movements %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>