config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root  'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  delete  '/logout', to:  'sessions#destroy'
  post  '/signup', to: 'users#create'
  # get   'static_pages/home'
  resources :users, only: [:new, :create, :show]
  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :movements, only: [:new, :create, :destroy]
  resources :movements do
    get :autocomplete_product_name, :on => :collection
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    MagRails Test Project by m3skalina
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "MagRails", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li>
            <%= link_to fa_icon('cube', text: 'Add Movement') , new_movement_path %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-cubes"></i> Products <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Products", products_path %></li>
              <li><%= link_to "Add Product", new_product_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Login", login_path %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>